add_newline = false

format = """
╭─$directory$git_branch$git_status$nodejs$bun$golang
╰─$character"""

[directory]
style = "cyan"
format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
format = " on [$branch]($style)"
style = "purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "red"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
